[phases.setup]
nixPkgs = [
    "python311Full",
    "nodejs_20"
]


[phases.install]
cmds = [
    "python -m ensurepip --default-pip",
    "python -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build",
    "python manage.py collectstatic --noinput"
]
