[phases.setup]
nixPkgs = [
    "python311",   # Instala Python 3.11
    "nodejs_20"    # Instala Node.js si necesitas manejar assets estáticos con npm
]

[phases.install]
cmds = [
    "pip install --upgrade pip",         # Asegura que pip esté actualizado
    "pip install -r requirements.txt"    # Instala dependencias
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn medicalAssistant.wsgi:application --bind 0.0.0.0:8000"
