[phases.setup]
nixPkgs = [
    "python311",  # No necesitas "python311Packages.pip", ya que el venv se crea solo
    "nodejs_20"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "npm run build",
    "python manage.py collectstatic --noinput"
]
