[phases.setup]
nixPkgs = [
    "python311Full",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel"
]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "honcho start"
