# Generated by Django 5.1.4 on 2025-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
