# Generated by Django 5.1.4 on 2025-02-07 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('dashboard', '0002_transcription_audio_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='transcription',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='transcription',
            index=models.Index(fields=['-publish'], name='dashboard_t_publish_8f97fb_idx'),
        ),
    ]
