# Generated by Django 5.1.4 on 2025-02-08 13:28
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_transcription_tags'),
    ]

    operations = [
        TrigramExtension(),
    ]
